server {
    listen 80;
    server_name 84.201.177.93 localhost foodgram.bazooza.ru;
    client_max_body_size 10M;

    location /media/ {
        alias /mediafiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
        proxy_pass http://backend:8000;
    }

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://backend:8000;
    }

    # Статика Django (включая админку)
    location /static/ {
        alias /staticfiles/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Статика фронтенда (включая шрифты)
    location /static/media/ {
        alias /app/build/static/media/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location ~* ^/(?!media/).*\.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root /app/build;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        root /app/build;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}